train <- read.table("X_train.txt",header=FALSE)
test <- read.table("X_test.txt",header=FALSE)
train <- rbind(train,test)
subject <- read.table("subject_train.txt",header = FALSE)
subjecttest <- read.table("subject_test.txt",header=FALSE)
subject <- rbind(subject,subjecttest)
headerc <- read.table("features.txt",header = FALSE)
activity <- read.table("y_train.txt",header = FALSE)
activitytest <- read.table("y_test.txt",header = FALSE)
activity <- rbind(activity,activitytest)
actlabel <- read.table("activity_labels.txt",header = FALSE)
activities <- as.character(actlabel[activity[[1]],2])
train <- cbind(subject,train,activities)
colnames(train) <- c("Subject",as.character(headerc[,2]),"Activity")
x <- grep("mean()", colnames(train),fixed=TRUE,value=FALSE)
y <- grep("std()", colnames(train),fixed=TRUE,value=FALSE)
x <- sort(c(x,y))
tidy <- train[,c(1,x,563)]
rm(train)
library(dplyr)
stidy <- tbl_df(tidy)
rm(tidy)
gtidy <- group_by(stidy, Subject, Activity)
ftidy <- summarise_each(gtidy,funs(mean))
write.table(ftidy, file="final_tidy.txt",row.names=FALSE)